### ISSUE TITLE
Question about use of timezone function 

### ISSUE THREAD

**Issue by rofiuddin** [ankane/groupdate.sql#7]
Thank you for all these very useful udf's here (including the recent `gd_quarter` function too 🎉)

This might be a stupid question but I failed to see through the reason why we used `CONVERT_TZ` twice here for some of the functions. for ex:

`CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(ts, '+00:00', time_zone), '%Y-%m-%d 00:00:00'), time_zone, '+00:00');`

once to convert timestamp to a desired timezone only to convert it back to UTC.

**Comment by ankane** [comment]
Hey @rofiuddin, good question. Groupdate.sql assumes your application stores times in UTC and expects times come back in UTC. For the function that returns dates (day, week, month, quarter, year), the 2nd conversion isn't really necessary (left over from when those functions returned times). Just pushed a change to remove it.

**Comment by ankane** [comment]
On further investigation, looks like it was a no-op for time zones with negative UTC offsets and returning the the incorrect date (shifted earlier by one) for time zones with positive UTC offsets.

**Comment by rofiuddin** [comment]
@ankane Thanks for the fix! I was also facing off-by-one bug. Glad I live few hour ahead of UTC and could be of help 😄

**Comment by ankane** [comment]
Thanks for asking about it. It's been that way for the past year and half (facepalm).
